version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: tlv-backend
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    develop:
      watch:
        - action: rebuild
          path: ./backend
